### ISSUE TITLE
How do you track history states and respond to a certain task?

### ISSUE THREAD

**Issue by teapotliid** [sweetpeach/Inspired#1]
Hi,
  I just read your training's code and I wonder how your model responds to a given query since you only used LM loss with cross entropy for your separate model A/B. For example, A asks one question and this sentence is then trained for model A. B responses A's question but this response is only trained for model B. How could your model_B generates this respone like B's response while your model_B couldn't know A's question?

**Comment by sweetpeach** [comment]
Hi!

Both of these separate models have the whole conversation history in their memory during training. You can check out line 100 and line 103 at training.py. "past" refers to the dialog history of both speakers (recommender & seeker).
